FROM node:20
WORKDIR /app/apps/worker
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
CMD ["node", "src/main.js"]
# Install Playwright browsers
RUN npx playwright install --with-deps
# For Appium, add: RUN npm i -g appium