FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

# Compile TypeScript
RUN npm run build

# Install Playwright system deps
RUN npx playwright install --with-deps

CMD ["node", "dist/main.js"]
